In [14]:
import numpy as np


In [15]:
a=np.array([[1,2,3],[2,9,0],[0,9,1]])
print(a)

[[1 2 3]
 [2 9 0]
 [0 9 1]]


In [7]:
c=np.array([1,2])
np.linalg.norm(c)

np.float64(2.23606797749979)

In [8]:
d=np.array([1,2,3,4,5])
np.linalg.norm(d)

np.float64(7.416198487095663)

In [9]:
#determinant 
np.linalg.det(a)

np.float64(59.000000000000014)

In [10]:
e=np.array([[1,2,3],[2,9,0],[0,9,-10.8]])
print(e)
print(np.linalg.det(e))

[[  1.    2.    3. ]
 [  2.    9.    0. ]
 [  0.    9.  -10.8]]
-5.95079541199082e-15


In [23]:
f=np.array([[1,2,3],[2,9,0]])
print(f)



[[1 2 3]
 [2 9 0]]


In [24]:
f @ f.T

array([[14, 20],
       [20, 85]])

In [25]:
f.T @ f

array([[ 5, 20,  3],
       [20, 85,  6],
       [ 3,  6,  9]])

In [26]:
#consider lower dimension matrix to determine determinant

print(np.linalg.det(f @ f.T))
#0 dependepnt
#non-zero independent

790.0000000000002


In [38]:
g=np.array([1,2])
h=np.array([2,3])
print(g)
print(h)
g_projection_h=np.dot(g,h) / np.linalg.norm(h) # to find magnitude of matrix h np.linalg.norm(b) 
h_projection_g=np.dot(g,h) / np.linalg.norm(g) # to find magnitude of matrix g np.linalg.norm(b) 

print("g sclar projecion over h",g_projection_h) #scalar project 
print("h sclar projecion over g",h_projection_g)

[1 2]
[2 3]
g projecion over h 2.2188007849009166
h projecion over g 3.5777087639996634


In [ ]:
)

In [28]:
8/(13**0.5)

2.2188007849009166

In [29]:
8/(5**0.5)

3.5777087639996634

In [39]:
#vector project

g=np.array([1,2])
h=np.array([2,3])
print(g)
print(h)
g_projection_h=(np.dot(g,h) / np.linalg.norm(h)) * (h/np.linalg.norm(h)) # to find magnitude of matrix h np.linalg.norm(b) 
h_projection_g=(np.dot(g,h) / np.linalg.norm(g)) * (g/np.linalg.norm(g))# to find magnitude of matrix g np.linalg.norm(b) 

print("g vector projecion over h",g_projection_h) #scalar project 
print("h vector projecion over g",h_projection_g)

[1 2]
[2 3]
g vector projecion over h [1.23076923 1.84615385]
h vector projecion over g [1.6 3.2]


In [45]:
v1=np.array([1,2,3])
v2=np.array([7,9,1])
v3=np.array([2,4,0])

def projection_a_over_b(g,h):
    return (np.dot(g,h) / np.linalg.norm(h)) * (h/np.linalg.norm(h))

x1=v1
#x2=v2-pro(v2 on v1)

x2=v2-(projection_a_over_b(v2,v1))

print(x1)
print(x2)

print(np.dot(x1,x2))

[1 2 3]
[ 5.  5. -5.]
0.0


In [47]:
x3=v3-(projection_a_over_b(v3,x1))-projection_a_over_b(v3,x2)
print(x3)

[-0.71428571  0.57142857 -0.14285714]


In [55]:
np.dot(x1,x2), np.dot(x1,x3), np.dot(x2,x3)

(np.float64(0.0),
 np.float64(-4.440892098500626e-16),
 np.float64(8.881784197001252e-16))

In [61]:
b1=np.array( [[1,2],[2,1]])
eigenvalues, eigevvectors=np.linalg.eig(b1)
print("eigen values:",eigenvalues)
print("eigen vectors:\n",eigevvectors)

eigen values: [ 3. -1.]
eigen vectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
#DIY1 - 