In [1]:
#NUMPY

import numpy as np

In [14]:
m1=[2,4,6,8.56,100]
m2=[1,3,5,7.23,99]
n1=np.array(m1)
print(type(n1))
print(n1)
print(n1.size) # total num of elementsin array
print(n1.ndim) #number of dimensions
print(n1.shape) #count along each axis
print(n1.dtype) #data type of an item in the array
print(n1.itemsize) #size in bytes of an item

<class 'numpy.ndarray'>
[  2.     4.     6.     8.56 100.  ]
5
1
(5,)
float64
8


In [18]:
m11=[[2,4,6,8,100],[1,3,5,7,99]]

n1=np.array(m11)
print(type(n1))
print(n1)
print(n1.size) # total num of elementsin array
print(n1.ndim) #number of dimensions
print(n1.shape) #count along each axis
print(n1.dtype) #data type of an item in the array
print(n1.itemsize) #size in bytes of an item

<class 'numpy.ndarray'>
[[  2   4   6   8 100]
 [  1   3   5   7  99]]
10
2
(2, 5)
int64
8


In [21]:
n34=np.random.randint(low=10,high=100,size=(3,4))
print(type(n34))
print(n34)
print(n34.size) # total num of elementsin array
print(n34.ndim) #number of dimensions
print(n34.shape) #count along each axis
print(n34.dtype) #data type of an item in the array
print(n34.itemsize) #size in bytes of an item

<class 'numpy.ndarray'>
[[10 50 55 75]
 [42 36 90 50]
 [70 36 64 86]]
12
2
(3, 4)
int32
4


In [28]:
import numpy as np
np.random.seed(23)
n35=np.random.randint(low=10,high=100,size=(3,4))
print(type(n35))
print(n35)
print(n35.size) # total num of elementsin array
print(n35.ndim) #number of dimensions
print(n35.shape) #count along each axis
print(n35.dtype) #data type of an item in the array
print(n35.itemsize) #size in bytes of an item

<class 'numpy.ndarray'>
[[93 50 83 64]
 [41 86 49 35]
 [61 16 55 22]]
12
2
(3, 4)
int32
4


In [32]:
n10=np.arange(10,15,1.5)#always returns one dimensionl array start, end and increment
print(n10)

[10.  11.5 13.  14.5]


In [33]:
n34=np.arange(12).reshape(4,3)
print(n34)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [35]:
n34=np.arange(12).reshape(4,-1)
print(n34)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
n34a=np.arange(12).reshape(3,4)
n34b=np.arange(100,112).reshape(3,4)
n34c=np.arange(200,224).reshape(4,6)

print(n34a)
print(n34b)
print(n34c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
[[200 201 202 203 204 205]
 [206 207 208 209 210 211]
 [212 213 214 215 216 217]
 [218 219 220 221 222 223]]


In [5]:
print(n34a+n34b) #matrix addtion

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]]


In [8]:
print(n34a+10.5) #matrix to scalar addition

[[10.5 11.5 12.5 13.5]
 [14.5 15.5 16.5 17.5]
 [18.5 19.5 20.5 21.5]]


In [9]:
print(n34a*10.5) #matrix to scalar multiplication

[[  0.   10.5  21.   31.5]
 [ 42.   52.5  63.   73.5]
 [ 84.   94.5 105.  115.5]]


In [12]:
print(n34a)
print(n34a ** 2) #

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [13]:
print(n34a)

print(n34a + [1,1,1,1]) #Cookies

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
#DIY, read more on broadcasting. numpy.org
#dot matrix or matrix multiplication learnt class
# N X M @ M X K = N X K

n341a=np.arange(12).reshape(3,4)
n341b=np.arange(3,15).reshape(4,3)

print(n341a)
print(n341b)
print(n341a@n341b)
print(np.matmul(n341a,n341b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 60  66  72]
 [180 202 224]
 [300 338 376]]
[[ 60  66  72]
 [180 202 224]
 [300 338 376]]


In [20]:
n342a=np.arange(4).reshape(2,2)
n342b=np.arange(5,9).reshape(2,2)

print(n342a)
print(n342b)
print(n342a@n342b)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]
[[ 7  8]
 [31 36]]


In [26]:
np.random.seed(23)
n34=np.random.randint(low=2,high=19,size=(3,4))
print(n34)
print(np.sum(n34))
print(np.sum(n34,axis=0))
print(np.sum(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
131
[38 38 24 31]
[39 46 46]


In [27]:
print(n34)
print(np.min(n34))
print(np.min(n34,axis=0))
print(np.min(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
4
[ 8 10  4  8]
[8 8 4]


In [28]:
print(n34)
print(np.max(n34))
print(np.max(n34,axis=0))
print(np.max(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
15
[15 14 11 13]
[11 15 15]


In [29]:
print(n34)
print(np.median(n34))
print(np.median(n34,axis=0))
print(np.median(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
10.5
[15. 14.  9. 10.]
[10.  11.5 13.5]


In [31]:

print(n34)
print(np.var(n34))
print(np.var(n34,axis=0))
print(np.var(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
10.57638888888889
[10.88888889  3.55555556  8.66666667  4.22222222]
[ 1.1875  9.25   19.25  ]


In [32]:
print(n34)
print(np.std(n34))
print(np.std(n34,axis=0))
print(np.std(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
3.2521360501813095
[3.29983165 1.88561808 2.94392029 2.05480467]
[1.08972474 3.04138127 4.38748219]


In [33]:
print(n34)
print(np.mean(n34))
print(np.mean(n34,axis=0))
print(np.mean(n34,axis=1))

[[ 8 10 11 10]
 [15 14  9  8]
 [15 14  4 13]]
10.916666666666666
[12.66666667 12.66666667  8.         10.33333333]
[ 9.75 11.5  11.5 ]


In [36]:
np.linspace(3,5,9)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [37]:
np.linspace(3,5,9,retstep=True)

(array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ]),
 np.float64(0.25))

In [38]:
np.linspace(3,5,9,retstep=False)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [41]:
np.random.seed(23)
n34=np.random.randint(low=1,high=20,size=(3,4))
print(n34)
for col in n34:
    print(col)

for value in np.nditer(n34):
    print(value)



[[ 7  9 10  9]
 [14 13  8  7]
 [14 13 18  3]]
[ 7  9 10  9]
[14 13  8  7]
[14 13 18  3]
7
9
10
9
14
13
8
7
14
13
18
3


In [43]:
np.random.seed(23)
n89=np.random.randint(low=10,high=101,size=(8,9))
print(n89)

[[ 93  50  83  64  41  86  49 100  35]
 [ 61  16  55  22  59  76  85  95  79]
 [ 74  22  31  58  51  89 100  72  67]
 [ 29  43  69  49  25  46  75  11  53]
 [ 25  96  93  68  35  76  84  45  66]
 [ 23  70  32  48  41  88  10  31  16]
 [ 42  42  24  41  88  93  90  80  76]
 [ 92  95  65  37  72  53  84  81  52]]


In [44]:
print(n89[0])

[ 93  50  83  64  41  86  49 100  35]


In [45]:
print(n89[0][0])

93


In [55]:
print(n89[0,0])

93


In [52]:
print(n89[-1,-1])

52


In [48]:
print(n89[0,-1])

35


In [49]:
print(n89[3,4])

25


In [54]:
print(n89[1:4]) #to print 2nd, 3rd and 4th row

[[ 61  16  55  22  59  76  85  95  79]
 [ 74  22  31  58  51  89 100  72  67]
 [ 29  43  69  49  25  46  75  11  53]]


In [56]:
print(n89[2:6,3:8]) #to print 2nd, 3rd and 4th row

[[ 58  51  89 100  72]
 [ 49  25  46  75  11]
 [ 68  35  76  84  45]
 [ 48  41  88  10  31]]


In [58]:
print(n89)
print("\n")
print(n89[1:4:2,1:6:2])

[[ 93  50  83  64  41  86  49 100  35]
 [ 61  16  55  22  59  76  85  95  79]
 [ 74  22  31  58  51  89 100  72  67]
 [ 29  43  69  49  25  46  75  11  53]
 [ 25  96  93  68  35  76  84  45  66]
 [ 23  70  32  48  41  88  10  31  16]
 [ 42  42  24  41  88  93  90  80  76]
 [ 92  95  65  37  72  53  84  81  52]]


[[16 22 76]
 [43 49 46]]


In [61]:
print(n89[[0,1,-2,-1,]]) #1st and last 2 rows

[[ 93  50  83  64  41  86  49 100  35]
 [ 61  16  55  22  59  76  85  95  79]
 [ 42  42  24  41  88  93  90  80  76]
 [ 92  95  65  37  72  53  84  81  52]]


In [63]:
print(n89[-5:]) #last 5 rows

[[29 43 69 49 25 46 75 11 53]
 [25 96 93 68 35 76 84 45 66]
 [23 70 32 48 41 88 10 31 16]
 [42 42 24 41 88 93 90 80 76]
 [92 95 65 37 72 53 84 81 52]]


In [77]:
print(n89)
print("\n")
print(n89[0:2])
#print(n89[0,1,-1],[0,1,2])

[[ 93  50  83  64  41  86  49 100  35]
 [ 61  16  55  22  59  76  85  95  79]
 [ 74  22  31  58  51  89 100  72  67]
 [ 29  43  69  49  25  46  75  11  53]
 [ 25  96  93  68  35  76  84  45  66]
 [ 23  70  32  48  41  88  10  31  16]
 [ 42  42  24  41  88  93  90  80  76]
 [ 92  95  65  37  72  53  84  81  52]]


[[ 93  50  83  64  41  86  49 100  35]
 [ 61  16  55  22  59  76  85  95  79]]


In [78]:
mask1=n89>50
print(mask1)

[[ True False  True  True False  True False  True False]
 [ True False  True False  True  True  True  True  True]
 [ True False False  True  True  True  True  True  True]
 [False False  True False False False  True False  True]
 [False  True  True  True False  True  True False  True]
 [False  True False False False  True False False False]
 [False False False False  True  True  True  True  True]
 [ True  True  True False  True  True  True  True  True]]


In [80]:

print(n89[mask1])

print("\n")
print(n89[ n89>50  ])

[ 93  83  64  86 100  61  55  59  76  85  95  79  74  58  51  89 100  72
  67  69  75  53  96  93  68  76  84  66  70  88  88  93  90  80  76  92
  95  65  72  53  84  81  52]


[ 93  83  64  86 100  61  55  59  76  85  95  79  74  58  51  89 100  72
  67  69  75  53  96  93  68  76  84  66  70  88  88  93  90  80  76  92
  95  65  72  53  84  81  52]


In [86]:
mask1=n89>50
mask2=(n89%2)==0

print(mask1,"\n",mask2)
print(mask2)

mask3= mask1 & mask2

print(n89[mask3])


[[ True False  True  True False  True False  True False]
 [ True False  True False  True  True  True  True  True]
 [ True False False  True  True  True  True  True  True]
 [False False  True False False False  True False  True]
 [False  True  True  True False  True  True False  True]
 [False  True False False False  True False False False]
 [False False False False  True  True  True  True  True]
 [ True  True  True False  True  True  True  True  True]] 
 [[False  True False  True False  True False  True False]
 [False  True False  True False  True False False False]
 [ True  True False  True False False  True  True False]
 [False False False False False  True False False False]
 [False  True False  True False  True  True False  True]
 [False  True  True  True False  True  True False  True]
 [ True  True  True False  True False  True  True  True]
 [ True False False False  True False  True False  True]]
[[False  True False  True False  True False  True False]
 [False  True False  True F

In [88]:
mask1=n89>75
mask2=n89<25
mask3= mask1 | mask2

print(n89[mask3])

[ 93  83  86 100  16  22  76  85  95  79  22  89 100  11  96  93  76  84
  23  88  10  16  24  88  93  90  80  76  92  95  84  81]


In [90]:
#n89[n89>50]=888
print(n89)

[[888  50 888 888  41 888  49 888  35]
 [888  16 888  22 888 888 888 888 888]
 [888  22  31 888 888 888 888 888 888]
 [ 29  43 888  49  25  46 888  11 888]
 [ 25 888 888 888  35 888 888  45 888]
 [ 23 888  32  48  41 888  10  31  16]
 [ 42  42  24  41 888 888 888 888 888]
 [888 888 888  37 888 888 888 888 888]]


In [93]:
print(n89)
print("\n")
r=np.vsplit(n89,2)
print(r)

[[888  50 888 888  41 888  49 888  35]
 [888  16 888  22 888 888 888 888 888]
 [888  22  31 888 888 888 888 888 888]
 [ 29  43 888  49  25  46 888  11 888]
 [ 25 888 888 888  35 888 888  45 888]
 [ 23 888  32  48  41 888  10  31  16]
 [ 42  42  24  41 888 888 888 888 888]
 [888 888 888  37 888 888 888 888 888]]


[array([[888,  50, 888, 888,  41, 888,  49, 888,  35],
       [888,  16, 888,  22, 888, 888, 888, 888, 888],
       [888,  22,  31, 888, 888, 888, 888, 888, 888],
       [ 29,  43, 888,  49,  25,  46, 888,  11, 888]], dtype=int32), array([[ 25, 888, 888, 888,  35, 888, 888,  45, 888],
       [ 23, 888,  32,  48,  41, 888,  10,  31,  16],
       [ 42,  42,  24,  41, 888, 888, 888, 888, 888],
       [888, 888, 888,  37, 888, 888, 888, 888, 888]], dtype=int32)]


In [95]:
print(np.vsplit(n89, [3,5])) # :3 -  0 to 2, 


[array([[888,  50, 888, 888,  41, 888,  49, 888,  35],
       [888,  16, 888,  22, 888, 888, 888, 888, 888],
       [888,  22,  31, 888, 888, 888, 888, 888, 888]], dtype=int32), array([[ 29,  43, 888,  49,  25,  46, 888,  11, 888],
       [ 25, 888, 888, 888,  35, 888, 888,  45, 888]], dtype=int32), array([[ 23, 888,  32,  48,  41, 888,  10,  31,  16],
       [ 42,  42,  24,  41, 888, 888, 888, 888, 888],
       [888, 888, 888,  37, 888, 888, 888, 888, 888]], dtype=int32)]


In [96]:
print(np.vsplit(n89, [2,3,4,6,7])) # :3 -  0 to 2, 

[array([[888,  50, 888, 888,  41, 888,  49, 888,  35],
       [888,  16, 888,  22, 888, 888, 888, 888, 888]], dtype=int32), array([[888,  22,  31, 888, 888, 888, 888, 888, 888]], dtype=int32), array([[ 29,  43, 888,  49,  25,  46, 888,  11, 888]], dtype=int32), array([[ 25, 888, 888, 888,  35, 888, 888,  45, 888],
       [ 23, 888,  32,  48,  41, 888,  10,  31,  16]], dtype=int32), array([[ 42,  42,  24,  41, 888, 888, 888, 888, 888]], dtype=int32), array([[888, 888, 888,  37, 888, 888, 888, 888, 888]], dtype=int32)]


In [ ]:
n34=np.arang(12).reshape(3,4)
n64=np.arange(100,124).reshape(6,4)
n36=np.arange(100,124).reshape(6,4)

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'